import types from '../constants/orders.constants'
import wsTypes from '../constants/ws.constants'
import ordersReducer, { INITIAL_STATE } from './orders.reducer'

describe('REDCUER: orders', () => {
  describe('action: OS_MESSAGE', () => {
    it('payload is not array', () => {
      const action = {
        type: wsTypes.OS_MESSAGE,
        payload: null,
      }
      expect(ordersReducer(INITIAL_STATE, action)).toEqual(INITIAL_STATE)
    })
    it('full payload', () => {
      const action = {
        type: wsTypes.OS_MESSAGE,
        payload: [
          'data.order',
          'bitfinex',
          [
            [
              33961681942,
              '1227',
              1337,
              'tBTCUSD',
              1573482478000,
              1573485373000,
              0.001,
              0.001,
              'EXCHANGE LIMIT',
              null,
              null,
              null,
              '0',
              'CANCELED',
              null,
              null,
              15,
              0,
              0,
              0,
              null,
              null,
              null,
              0,
              0,
              null,
              null,
              null,
              'API>BFX',
              null,
              null,
              null,
            ],
          ],
        ],
      }
      expect(ordersReducer(INITIAL_STATE, action)).toEqual({
        ...INITIAL_STATE,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.001,
            originalAmount: 0.001,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
      })
    })
  })

  describe('action: ON_MESSAGE', () => {
    it('payload is not array', () => {
      const action = {
        type: wsTypes.ON_MESSAGE,
        payload: null,
      }
      expect(ordersReducer(INITIAL_STATE, action)).toEqual(INITIAL_STATE)
    })
    it('full payload, pair is all, exited order, status changed', () => {
      const initialState = {
        ...INITIAL_STATE,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.001,
            originalAmount: 0.001,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'ACTIVE',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
      }
      const action = {
        type: wsTypes.ON_MESSAGE,
        payload: [
          'data.order',
          'bitfinex',
          [
            33961681942,
            '1227',
            1337,
            'tBTCUSD',
            1573482478000,
            1573485373000,
            0.5,
            0.5,
            'EXCHANGE LIMIT',
            null,
            null,
            null,
            '0',
            'CANCELED',
            null,
            null,
            15,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            null,
          ],
        ],
      }
      expect(ordersReducer(initialState, action)).toEqual({
        ...INITIAL_STATE,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
            isStatusChanged: true,
          },
        },
      })
    })
    it('full payload, pair is all, exited order, status the same', () => {
      const initialState = {
        ...INITIAL_STATE,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.001,
            originalAmount: 0.001,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'ACTIVE',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
      }
      const action = {
        type: wsTypes.ON_MESSAGE,
        payload: [
          'data.order',
          'bitfinex',
          [
            33961681942,
            '1227',
            1337,
            'tBTCUSD',
            1573482478000,
            1573485373000,
            0.5,
            0.5,
            'EXCHANGE LIMIT',
            null,
            null,
            null,
            '0',
            'ACTIVE',
            null,
            null,
            15,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            null,
          ],
        ],
      }
      expect(ordersReducer(initialState, action)).toEqual({
        ...INITIAL_STATE,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'ACTIVE',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
            isStatusChanged: false,
          },
        },
      })
    })
    it('full payload, pair is all, order is not existed', () => {
      const action = {
        type: wsTypes.ON_MESSAGE,
        payload: [
          'data.order',
          'bitfinex',
          [
            33961681942,
            '1227',
            1337,
            'tBTCUSD',
            1573482478000,
            1573485373000,
            0.5,
            0.5,
            'EXCHANGE LIMIT',
            null,
            null,
            null,
            '0',
            'CANCELED',
            null,
            null,
            15,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            null,
          ],
        ],
      }
      const initialState = {
        ...INITIAL_STATE,
        all: {},
      }
      expect(ordersReducer(initialState, action)).toEqual({
        ...initialState,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
            isStatusChanged: undefined,
          },
        },
      })
    })
    it('full payload, pair is not all, order is not existed', () => {
      const action = {
        type: wsTypes.ON_MESSAGE,
        meta: {
          pair: 'BTCUSD',
        },
        payload: [
          'data.order',
          'bitfinex',
          [
            33961681942,
            '1227',
            1337,
            'tBTCUSD',
            1573482478000,
            1573485373000,
            0.5,
            0.5,
            'EXCHANGE LIMIT',
            null,
            null,
            null,
            '0',
            'CANCELED',
            null,
            null,
            15,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            null,
          ],
        ],
      }
      const initialState = {
        ...INITIAL_STATE,
        all: {},
      }
      expect(ordersReducer(initialState, action)).toEqual({
        ...initialState,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
            isStatusChanged: undefined,
          },
        },
        BTCUSD: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
            isStatusChanged: undefined,
          },
        },
      })
    })
  })

  describe('action: FETCH_ORDER_HISTORY_SUCCESS', () => {
    it('payload is not array', () => {
      const initialState = {
        ...INITIAL_STATE,
        all: {},
      }
      const action = {
        type: types.FETCH_ORDER_HISTORY_SUCCESS,
        payload: null,
      }
      expect(ordersReducer(initialState, action)).toEqual(initialState)
    })
    it('full payload, pair is exists', () => {
      const initialState = {
        ...INITIAL_STATE,
        hist_BTCUSD: {
          11111111111: {},
        },
      }
      const action = {
        type: types.FETCH_ORDER_HISTORY_SUCCESS,
        meta: { pair: 'BTCUSD' },
        payload: [
          [
            33950998275,
            null,
            1573476747887,
            'tBTCUSD',
            1573476748000,
            1573476748000,
            -0.5,
            -0.5,
            'LIMIT',
            null,
            null,
            null,
            0,
            'ACTIVE',
            null,
            null,
            220,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'BFX',
            null,
            null,
            null,
          ],
          [
            33950998276,
            null,
            1573476812756,
            'tBTCUSD',
            1573476813000,
            1573476813000,
            0.0026,
            0.0026,
            'LIMIT',
            null,
            null,
            null,
            0,
            'ACTIVE',
            null,
            null,
            8000,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'BFX',
            null,
            null,
            null,
          ],
        ],
      }
      expect(ordersReducer(initialState, action)).toEqual({
        ...initialState,
        hist_BTCUSD: {
          ...initialState.hist_BTCUSD,
          33950998275: {
            id: 33950998275,
            group_id: null,
            client_id: 1573476747887,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573476748000,
            placed: 1573476748000,
            amount: -0.5,
            originalAmount: -0.5,
            type: 'LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: 0,
            status: 'ACTIVE',
            price: 220,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
          33950998276: {
            id: 33950998276,
            group_id: null,
            client_id: 1573476812756,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573476813000,
            placed: 1573476813000,
            amount: 0.0026,
            originalAmount: 0.0026,
            type: 'LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: 0,
            status: 'ACTIVE',
            price: 8000,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
      })
    })
  })

  describe('action: OC_MESSAGE', () => {
    it('payload is not array', () => {
      const initialState = {
        ...INITIAL_STATE,
        all: {},
      }
      const action = {
        type: wsTypes.OC_MESSAGE,
        payload: null,
      }
      expect(ordersReducer(initialState, action)).toEqual(initialState)
    })
    it('full payload, order is existed', () => {
      const initialState = {
        ...INITIAL_STATE,
        all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
          999999999: {
            id: 999999999,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
        BTCUSD: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
      }
      const action = {
        type: wsTypes.OC_MESSAGE,
        payload: [
          'data.order',
          'bitfinex',
          [
            33961681942,
            '1227',
            1337,
            'tBTCUSD',
            1573482478000,
            1573485373000,
            0.5,
            0.5,
            'EXCHANGE LIMIT',
            null,
            null,
            null,
            '0',
            'CANCELED',
            null,
            null,
            15,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            null,
            null,
            null,
            'API>BFX',
            null,
            null,
            null,
          ],
        ],
      }
      expect(ordersReducer(initialState, action)).toEqual({
        hist_all: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
        hist_BTCUSD: {
          33961681942: {
            id: 33961681942,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
        BTCUSD: {},
        all: {
          999999999: {
            id: 999999999,
            group_id: '1227',
            client_id: 1337,
            baseCcy: 'BTC',
            quoteCcy: 'USD',
            pair: 'BTC/USD',
            symbol: 'BTCUSD',
            mts_create: 1573482478000,
            placed: 1573485373000,
            amount: 0.5,
            originalAmount: 0.5,
            type: 'EXCHANGE LIMIT',
            type_prev: null,
            mts_tif: null,
            flags: '0',
            status: 'CANCELED',
            price: 15,
            priceAverage: 0,
            price_trailing: 0,
            price_aux_limit: 0,
            notify: 0,
            hidden: 0,
            placed_id: null,
            meta: null,
          },
        },
      })
    })
  })
})
