name: Pull request verify workflow

on:
  # Trigger the workflow on push or pull request,
  # but only for the default(staging) branch
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
    types: [opened, labeled, synchronize, ready_for_review]

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Run Build Check
        run: npm run build

      - name: Run Lint Check
        run: npm run lint

      - name: Run Test Check
        run: npm run test

      - name: Annotate Checks
        uses: tarcisiozf/ci-checks-action@master
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          checks: '[
            {
              "name": "build",
              "fileName": ".build-report.json",
              "prChangesOnly": true
            },
            {
              "name": "lint",
              "fileName": ".lint-report.json",
              "prChangesOnly": true
            },
            {
              "name": "test",
              "fileName": ".test-report.json",
              "prChangesOnly": false
            }
          ]'
